### ISSUE TITLE
Heatmap issue - d.rendered not working

### ISSUE THREAD

**Issue by AlexHancock-SB** [llooker/custom_visualizations#25]
Hi, we've been using the heatmap (thanks).

As of Looker 3.44 (may have been 3.42 but we skipped a version), it looks like the heatmap no longer displays the dimension row text (displaying the Null symbol instead). 

![image](https://cloud.githubusercontent.com/assets/7300003/14825327/516cca4e-0bd1-11e6-9a3a-28e42fbd905c.png)

**Comment by ericfeinstein** [comment]
Are you using the heatmap-example or heatmap-three-measure-cell?

**Comment by AlexHancock-SB** [comment]
heatmap-example

**Comment by ericfeinstein** [comment]
Can you replace it with the version here?

https://github.com/llooker/custom_visualizations/blob/master/heatmap-example.js

I updated the above with a fix. You will need to remove the slashes before each line  ('//')

**Comment by AlexHancock-SB** [comment]
This now works again great thanks!
